### ISSUE TITLE
Redesign for the meta fields content app

### ISSUE THREAD

**Issue by patrickdemooij9** [patrickdemooij9/SeoToolkit.Umbraco#53]
A few things that (I think) should be done here:

- [x] Make it more in line with the document type variant. We'll probably have sitemap specific options here in the future.
- [ ] Show previews for the user. Will make it a nicer view
- [ ] Ability to disable preview so that the user is able to see what the actual value is
- [ ] Ability to only edit a single field. Should make it easier and faster if you only want to edit a certain thing
